spring.security.user.name=user
spring.security.user.password=pass

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

spring.app.jwtSecret=mySecretKey123456$$$
spring.app.jwtExpirationMs=300000000000000000000