spring.application.name=sb-ecom
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

project.image=images/

spring.app.jwtSecret=mySecretKey123456jklasdfkjalsdkfnlasdkjfnlaskjdnflaskdjnflaskdjnf
spring.app.jwtExpirationMs=30000000
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.sql=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.ecommerce.project=DEBUG

spring.ecom.app.jwtCookieName=springBootEcom